### ISSUE TITLE
Rich Text Editor escapes valid Markdown

### ISSUE THREAD

**Issue by lsolesen** [decaporg/decap-cms#4360]
**Describe the bug**

The editor escapes valid markdown used in Jekyll. I have the following Markdown in Jekyll

    *[MY]: My Abbr
    [Link to my post]({% link _post/mypost.md %})

When toggling the Rich Text editor, I end up with the code escaped.

**To Reproduce**

See this diff saved after opening the .md file with the Rich text editor.

https://github.com/motionsplan/motionsplan-dk-jekyll/pull/52/files

Links and abbr. is escaped.

**Expected behavior**

Making sure that the abbr and links are left alone.

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.10.16]
 - Git provider: [GitHub] and Netlify
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

https://github.com/motionsplan/motionsplan-dk-jekyll/blob/master/admin/config.yml

**Additional context**

**Comment by Daeruin** [comment]
I am also experiencing this behavior in Netlify CMS 2.0.0 with Bitbucket on MacOS Catalina using Chrome 85.0.4183.102.

**Comment by lsolesen** [comment]
It seems that a similar issue was raised here https://github.com/netlify/netlify-cms/issues/2386, and fixed here https://github.com/netlify/netlify-cms/pull/3646 just for foot notes.

It seems that --- is also escaped when switching between rich text and markdown.

**Comment by martinjagodic** [comment]
Closing as stale

**Comment by Zottelchen** [comment]
@martinjagodic This issue still exists. Personally I am using [[Wikilinks]] and the rich text editor still breaks them.

**Comment by martinjagodic** [comment]
@Zottelchen did you test that with the latest release?

**Comment by Zottelchen** [comment]
@martinjagodic Yep, still happens with `decap-cms-app 3.0.5/decap-cms-core 3.2.2/decap-cms 3.0.5`.
![image](https://github.com/decaporg/decap-cms/assets/5148555/4757389a-fa0d-4597-8dda-01da9fe1c1bc)
